config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_theme.rasi:
    src: config/rofi/theme.rasi
    dst: ~/.config/rofi/theme.rasi
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dunstrc.template:
    src: config/dunst/dunstrc.template
    dst: ~/.config/dunst/dunstrc.template
  f_hyprland.conf:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
  d_bin:
    src: bin
    dst: ~/.bin
    upignore:
    - '*/__pycache__'
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_profile:
    src: profile
    dst: ~/.profile
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  d_repos.conf:
    src: etc/portage/repos.conf
    dst: /etc/portage/repos.conf
  f_make.conf:
    src: etc/portage/make.conf
    dst: /etc/portage/make.conf
  d_env:
    src: etc/portage/env
    dst: /etc/portage/env
  d_package.accept_keywords:
    src: etc/portage/package.accept_keywords
    dst: /etc/portage/package.accept_keywords
  d_package.env:
    src: etc/portage/package.env
    dst: /etc/portage/package.env
  d_package.use:
    src: etc/portage/package.use
    dst: /etc/portage/package.use
  d_patches:
    src: etc/portage/patches
    dst: /etc/portage/patches
  d_postsync.d:
    src: etc/portage/postsync.d
    dst: /etc/portage/postsync.d
  f_world:
    src: var/lib/portage/world
    dst: /var/lib/portage/world
profiles:
  shallot:
    dotfiles:
    - f_config.fish
    - d_functions
    - f_config.rasi
    - f_theme.rasi
    - f_bashrc
    - f_dunstrc.template
    - f_hyprland.conf
    - f_config
    - d_bin
    - f_tmux.conf
    - d_waybar
    - f_profile
    - d_nvim
    - f_alacritty.yml
    - d_repos.conf
    - f_make.conf
    - d_env
    - d_package.accept_keywords
    - d_package.env
    - d_package.use
    - d_patches
    - d_postsync.d
    - f_world
