config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_theme.rasi:
    src: config/rofi/theme.rasi
    dst: ~/.config/rofi/theme.rasi
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dunstrc.template:
    src: config/dunst/dunstrc.template
    dst: ~/.config/dunst/dunstrc.template
profiles:
  shallot:
    dotfiles:
    - f_config.fish
    - d_functions
    - f_config.rasi
    - f_theme.rasi
    - f_bashrc
    - f_dunstrc.template
