config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
profiles:
  shallot:
    dotfiles:
    - f_config.fish
    - d_functions
