config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  d_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
  f_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_theme.rasi:
    src: config/rofi/theme.rasi
    dst: ~/.config/rofi/theme.rasi
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dunstrc.template:
    src: config/dunst/dunstrc.template
    dst: ~/.config/dunst/dunstrc.template
  f_hyprland.conf:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
  d_bin:
    src: bin
    dst: ~/.bin
    upignore:
    - '*/__pycache__'
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_profile:
    src: profile
    dst: ~/.profile
profiles:
  shallot:
    dotfiles:
    - f_config.fish
    - d_functions
    - f_config.rasi
    - f_theme.rasi
    - f_bashrc
    - f_dunstrc.template
    - f_hyprland.conf
    - f_config
    - d_bin
    - f_tmux.conf
    - d_waybar
    - f_profile
